name: ci

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build with Maven
        run: mvn clean install

      - 
        name: Build & push Docker image
        uses: docker/build-push-action@v5
        with:
          image: getting-started-service
          tags: latest
          registry: docker.io
          dockerfile: Dockerfile
